import type { WorksWheelItem } from "@/components/ui/works-wheel";

// Landscape language cards at the wheel's 1.45:1 ratio, generated by
// scripts/generate-code-art.mjs.
const art = (slug: string) => `/code-art/wide/${slug}.svg`;

export type Work = WorksWheelItem & {
  /** What the snippet on the card does. */
  medium: string;
  /** ISO date of the last edit. */
  updated: string;
  views: number;
  saves: number;
  status: "Published" | "Draft";
};

// Placeholder stats until works come from a real source. Ordered so
// neighbouring cards on the ring contrast in colour.
export const WORKS: Work[] = [
  {
    id: "python",
    title: "Python",
    image: art("python"),
    medium: "Fibonacci generator",
    updated: "2026-09-28",
    views: 18420,
    saves: 1204,
    status: "Published",
  },
  {
    id: "java",
    title: "Java",
    image: art("java"),
    medium: "Hello-world main class",
    updated: "2026-09-21",
    views: 9310,
    saves: 688,
    status: "Published",
  },
  {
    id: "cpp",
    title: "C++",
    image: art("cpp"),
    medium: "Range-for over a vector",
    updated: "2026-10-02",
    views: 12740,
    saves: 1016,
    status: "Published",
  },
  {
    id: "javascript",
    title: "JavaScript",
    image: art("javascript"),
    medium: "Greeting in the DOM",
    updated: "2026-10-06",
    views: 26930,
    saves: 2471,
    status: "Published",
  },
  {
    id: "rust",
    title: "Rust",
    image: art("rust"),
    medium: "Looping an array",
    updated: "2026-10-08",
    views: 3280,
    saves: 241,
    status: "Draft",
  },
  {
    id: "go",
    title: "Go",
    image: art("go"),
    medium: "Goroutine and channel",
    updated: "2026-09-12",
    views: 11860,
    saves: 1032,
    status: "Published",
  },
  {
    id: "kotlin",
    title: "Kotlin",
    image: art("kotlin"),
    medium: "Copying a data class",
    updated: "2026-08-30",
    views: 7645,
    saves: 512,
    status: "Published",
  },
  {
    id: "typescript",
    title: "TypeScript",
    image: art("typescript"),
    medium: "Typed user model",
    updated: "2026-10-04",
    views: 22740,
    saves: 2016,
    status: "Published",
  },
  {
    id: "swift",
    title: "Swift",
    image: art("swift"),
    medium: "Struct with interpolation",
    updated: "2026-09-05",
    views: 6105,
    saves: 473,
    status: "Published",
  },
  {
    id: "csharp",
    title: "C#",
    image: art("csharp"),
    medium: "Interpolated foreach",
    updated: "2026-07-19",
    views: 8930,
    saves: 701,
    status: "Published",
  },
  {
    id: "ruby",
    title: "Ruby",
    image: art("ruby"),
    medium: "Blocks and iterators",
    updated: "2026-09-17",
    views: 4410,
    saves: 365,
    status: "Published",
  },
  {
    id: "php",
    title: "PHP",
    image: art("php"),
    medium: "Looping an array",
    updated: "2026-10-07",
    views: 1190,
    saves: 86,
    status: "Draft",
  },
];
